"use client";

import { CarIcon, Shield, Eye, Lock, Globe, FileText, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import Link from "next/link";

export default function PrivacyPage() {
  return (
    <div>
      {/* Hero Section */}
      <section className="relative py-16 md:py-24 bg-gradient-to-r from-teal-900 via-teal-800 to-teal-700 text-white overflow-hidden">
        {/* Abstract shapes */}
        <div className="absolute inset-0 overflow-hidden opacity-10">
          <div className="absolute -right-40 -top-40 w-80 h-80 bg-teal-400 rounded-full"></div>
          <div className="absolute -left-20 bottom-10 w-60 h-60 bg-teal-300 rounded-full"></div>
        </div>

        <div className="container mx-auto px-4 relative z-10">
          <div className="max-w-3xl mx-auto text-center">
            <h1 className="text-4xl md:text-5xl font-bold mb-4 font-heading">
              Privacy Policy
            </h1>
            {/* <p className="text-xl text-teal-100 mb-6">
              Last updated: October 11, 2025
            </p> */}
            <p className="text-lg text-teal-100">
              This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>
          </div>
        </div>
      </section>

      {/* Introduction */}
      <section className="py-16 bg-white">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <p className="text-lg text-slate-600 mb-8">
              We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.
            </p>

            <Card className="p-8">
              <h2 className="text-3xl font-bold text-slate-800 mb-6 flex items-center gap-3">
                <FileText className="h-8 w-8 text-teal-700" />
                Interpretation and Definitions
              </h2>
              
              <div className="space-y-6">
                <div>
                  <h3 className="text-xl font-semibold text-slate-800 mb-3">Interpretation</h3>
                  <p className="text-slate-600">
                    The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                  </p>
                </div>

                <div>
                  <h3 className="text-xl font-semibold text-slate-800 mb-4">Definitions</h3>
                  <p className="text-slate-600 mb-4">For the purposes of this Privacy Policy:</p>
                  
                  <div className="grid gap-4">
                    {[
                      { term: "Account", definition: "means a unique account created for You to access our Service or parts of our Service." },
                      { term: "Affiliate", definition: "means an entity that controls, is controlled by, or is under common control with a party, where \"control\" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority." },
                      { term: "Company", definition: "(referred to as either \"the Company\", \"We\", \"Us\" or \"Our\" in this Agreement) refers to Rathagala.lk." },
                      { term: "Cookies", definition: "are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses." },
                      { term: "Country", definition: "refers to: Sri Lanka" },
                      { term: "Device", definition: "means any device that can access the Service such as a computer, a cell phone or a digital tablet." },
                      { term: "Personal Data", definition: "is any information that relates to an identified or identifiable individual." },
                      { term: "Service", definition: "refers to the Website." },
                      { term: "Service Provider", definition: "means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used." },
                      { term: "Usage Data", definition: "refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit)." },
                      { term: "Website", definition: "refers to Rathagala.lk, accessible from https://rathagala.lk/" },
                      { term: "You", definition: "means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable." }
                    ].map((item, index) => (
                      <div key={index} className="border-l-4 border-teal-200 pl-4 py-2">
                        <strong className="text-slate-800">{item.term}:</strong> <span className="text-slate-600">{item.definition}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </Card>
          </div>
        </div>
      </section>

      {/* Data Collection */}
      <section className="py-16 bg-slate-50">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <Card className="p-8">
              <h2 className="text-3xl font-bold text-slate-800 mb-6 flex items-center gap-3">
                <Eye className="h-8 w-8 text-teal-700" />
                Collecting and Using Your Personal Data
              </h2>

              <div className="space-y-8">
                <div>
                  <h3 className="text-2xl font-semibold text-slate-800 mb-4">Types of Data Collected</h3>
                  
                  <div className="space-y-6">
                    <div>
                      <h4 className="text-xl font-semibold text-slate-800 mb-3">Personal Data</h4>
                      <p className="text-slate-600 mb-3">
                        While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
                      </p>
                      <ul className="list-disc pl-6 text-slate-600 space-y-1">
                        <li>Email address</li>
                        <li>First name and last name</li>
                        <li>Phone number</li>
                        <li>Address, State, Province, ZIP/Postal code, City</li>
                        <li>Usage Data</li>
                      </ul>
                    </div>

                    <div>
                      <h4 className="text-xl font-semibold text-slate-800 mb-3">Usage Data</h4>
                      <p className="text-slate-600 mb-3">
                        Usage Data is collected automatically when using the Service.
                      </p>
                      <p className="text-slate-600 mb-3">
                        Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                      </p>
                      <p className="text-slate-600">
                        When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
                      </p>
                    </div>
                  </div>
                </div>

                <div>
                  <h3 className="text-2xl font-semibold text-slate-800 mb-4">Tracking Technologies and Cookies</h3>
                  <p className="text-slate-600 mb-4">
                    We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
                  </p>
                  
                  <div className="grid md:grid-cols-3 gap-4 mt-6">
                    <div className="bg-teal-50 p-4 rounded-lg">
                      <h5 className="font-semibold text-slate-800 mb-2">Necessary / Essential Cookies</h5>
                      <p className="text-sm text-slate-600">Session Cookies essential to provide services and authenticate users.</p>
                    </div>
                    <div className="bg-teal-50 p-4 rounded-lg">
                      <h5 className="font-semibold text-slate-800 mb-2">Acceptance Cookies</h5>
                      <p className="text-sm text-slate-600">Persistent Cookies that identify if users have accepted cookie usage.</p>
                    </div>
                    <div className="bg-teal-50 p-4 rounded-lg">
                      <h5 className="font-semibold text-slate-800 mb-2">Functionality Cookies</h5>
                      <p className="text-sm text-slate-600">Persistent Cookies that remember your choices and preferences.</p>
                    </div>
                  </div>
                </div>
              </div>
            </Card>
          </div>
        </div>
      </section>

      {/* Data Usage */}
      <section className="py-16 bg-white">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <Card className="p-8">
              <h2 className="text-3xl font-bold text-slate-800 mb-6 flex items-center gap-3">
                <Globe className="h-8 w-8 text-teal-700" />
                Use of Your Personal Data
              </h2>

              <p className="text-slate-600 mb-6">The Company may use Personal Data for the following purposes:</p>
              
              <ul className="space-y-3 text-slate-600">
                <li className="flex items-start gap-3">
                  <div className="w-2 h-2 bg-teal-600 rounded-full mt-2 flex-shrink-0"></div>
                  <span><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</span>
                </li>
                <li className="flex items-start gap-3">
                  <div className="w-2 h-2 bg-teal-600 rounded-full mt-2 flex-shrink-0"></div>
                  <span><strong>To manage Your Account</strong>: to manage Your registration as a user of the Service.</span>
                </li>
                <li className="flex items-start gap-3">
                  <div className="w-2 h-2 bg-teal-600 rounded-full mt-2 flex-shrink-0"></div>
                  <span><strong>For the performance of a contract</strong>: the development, compliance and undertaking of the purchase contract.</span>
                </li>
                <li className="flex items-start gap-3">
                  <div className="w-2 h-2 bg-teal-600 rounded-full mt-2 flex-shrink-0"></div>
                  <span><strong>To contact You</strong>: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</span>
                </li>
                <li className="flex items-start gap-3">
                  <div className="w-2 h-2 bg-teal-600 rounded-full mt-2 flex-shrink-0"></div>
                  <span><strong>To provide You with news and offers</strong> about goods, services and events similar to those you have purchased or inquired about.</span>
                </li>
              </ul>

              <div className="mt-8">
                <h3 className="text-xl font-semibold text-slate-800 mb-4">We may share Your personal information in the following situations:</h3>
                <ul className="space-y-2 text-slate-600">
                  <li>• <strong>With Service Providers:</strong> To monitor and analyze the use of our Service</li>
                  <li>• <strong>For business transfers:</strong> During mergers, acquisitions, or asset sales</li>
                  <li>• <strong>With Affiliates:</strong> Our parent company and subsidiaries</li>
                  <li>• <strong>With business partners:</strong> To offer certain products or services</li>
                  <li>• <strong>With Your consent:</strong> For any other purpose with Your consent</li>
                </ul>
              </div>
            </Card>
          </div>
        </div>
      </section>

      {/* Security & Rights */}
      <section className="py-16 bg-slate-50">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <div className="grid md:grid-cols-2 gap-8">
              <Card className="p-6">
                <h3 className="text-xl font-semibold text-slate-800 mb-4 flex items-center gap-2">
                  <Shield className="h-6 w-6 text-teal-700" />
                  Security of Your Personal Data
                </h3>
                <p className="text-slate-600">
                  The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.
                </p>
              </Card>

              <Card className="p-6">
                <h3 className="text-xl font-semibold text-slate-800 mb-4 flex items-center gap-2">
                  <Lock className="h-6 w-6 text-teal-700" />
                  Delete Your Personal Data
                </h3>
                <p className="text-slate-600">
                  You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. You may update, amend, or delete Your information through Your Account settings or by contacting Us.
                </p>
              </Card>

              <Card className="p-6">
                <h3 className="text-xl font-semibold text-slate-800 mb-4 flex items-center gap-2">
                  <Users className="h-6 w-6 text-teal-700" />
                  Children's Privacy
                </h3>
                <p className="text-slate-600">
                  Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are aware that Your child has provided Us with Personal Data, please contact Us.
                </p>
              </Card>

              <Card className="p-6">
                <h3 className="text-xl font-semibold text-slate-800 mb-4">Changes to this Privacy Policy</h3>
                <p className="text-slate-600">
                  We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date at the top of this Privacy Policy.
                </p>
              </Card>
            </div>
          </div>
        </div>
      </section>

      {/* Contact Section */}
      <section className="py-16 bg-teal-800 text-white">
        <div className="container mx-auto px-4">
          <div className="max-w-3xl mx-auto text-center">
            <h2 className="text-3xl font-bold mb-4">Contact Us</h2>
            <p className="text-xl text-teal-100 mb-8">
              If you have any questions about this Privacy Policy, You can contact us:
            </p>
            <div className="space-y-4">
              <p className="text-lg">
                <strong>By email:</strong>{" "}
                <a href="mailto:info@rathagala.lk" className="text-teal-200 hover:text-white underline">
                  info@rathagala.lk
                </a>
              </p>
              <p className="text-lg">
                <strong>By visiting our contact page:</strong>{" "}
                <a href="https://rathagala.lk/contact" className="text-teal-200 hover:text-white underline">
                  https://rathagala.lk/contact
                </a>
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-16 bg-slate-50">
        <div className="container mx-auto px-4">
          <div className="max-w-3xl mx-auto text-center">
            <h2 className="text-3xl font-bold text-slate-800 mb-4">
              Ready to Get Started?
            </h2>
            <p className="text-lg text-slate-600 mb-8">
              Join thousands of users who trust Rathagala.lk with their vehicle trading needs
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link href="/sell">
                <Button
                  className="bg-teal-700 hover:bg-teal-600 text-white"
                  size="lg"
                >
                  List Your Vehicle
                </Button>
              </Link>
              <Link href="/">
                <Button
                  variant="outline"
                  className="border-teal-700 text-teal-700 hover:bg-teal-50"
                  size="lg"
                >
                  Browse Vehicles
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}