"use client";

import { useFormContext } from "react-hook-form";
import { CreateAdSchema } from "@/server/routes/ad/ad.schemas";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { Button } from "@/components/ui/button";
import { FormField, FormItem, FormLabel, FormControl, FormMessage, FormDescription } from "@/components/ui/form";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { DynamicVehicleFieldsStep2 } from "@/app/(frontend)/(landing)/sell/new/_components/dynamic-vehicle-fields-step-2";
import { Sparkles, PlusCircle } from "lucide-react";

import { toast } from "sonner";

interface Step2Props {
  onBack: () => void;
  onNext: () => void;
  canProceed: boolean;
}

export function Step2VehicleDetails({ onBack, onNext, canProceed }: Step2Props) {
  const form = useFormContext<CreateAdSchema>();
  const listingType = form.watch("listingType");

  const handleNextClick = () => {
    if (!canProceed) {
      const values = form.getValues();
      const missing: string[] = [];
      
      if (values.listingType === "SELL") {
        if (!values.description) missing.push("Description");

        if (values.type === "CAR") {
          if (!values.fuelType) missing.push("Fuel Type");
          if (!values.transmission) missing.push("Transmission");
        } else if (values.type === "MOTORCYCLE") {
          if (!values.engineCapacity) missing.push("Engine Capacity");
        } else if (["THREE_WHEEL", "BUS", "LORRY", "TRACTOR"].includes(values.type)) {
          if (!values.fuelType) missing.push("Fuel Type");
        }
      } else {
        if (!values.description) missing.push("Description");
      }

      toast.error("Please complete Step 2 details", {
        description: `Missing: ${missing.join(", ") || "Required details"}`,
        duration: 4000
      });
      return;
    }
    onNext();
  };

  const formatPrice = (value: number | undefined) => {
    if (!value) return "";
    return new Intl.NumberFormat('en-LK', { style: 'currency', currency: 'LKR', maximumFractionDigits: 0 }).format(value);
  };

  const autoGenerateDescription = () => {
    const v = form.getValues();
    if (v.listingType !== "SELL") return;
    
    let newDesc = `For sale: ${v.condition || "Used"} ${v.brand || ""} ${v.model || ""} ${v.manufacturedYear || v.modelYear || ""}`.trim();
    if (newDesc.endsWith("Used") || newDesc.endsWith("sale:")) newDesc = "Vehicle for sale";
    
    newDesc += `.\n\nExcellent condition, carefully used.`;
    if (v.mileage) newDesc += `\nMileage: ${v.mileage} km.`;
    if (v.engineCapacity) newDesc += `\nEngine: ${v.engineCapacity} cc.`;
    if (v.transmission) newDesc += `\nTransmission: ${v.transmission}.`;
    if (v.fuelType) newDesc += `\nFuel Type: ${v.fuelType}.`;
    
    newDesc += `\n\nLooking for a quick sale. Please contact for more details.`;
    form.setValue("description", newDesc, { shouldValidate: true });
    toast.success("Description auto-generated!");
  };

  const featureChips = ["A/C", "Power Steering", "Power Windows", "ABS", "Reverse Camera", "Alloy Wheels", "Sunroof", "First Owner"];
  const addFeature = (feature: string) => {
    const currentDesc = form.getValues("description") || "";
    const newDesc = currentDesc ? `${currentDesc}\n- ${feature}` : `- ${feature}`;
    form.setValue("description", newDesc, { shouldValidate: true });
  };

  return (
    <div className="space-y-6">
      {listingType !== "SELL" ? (
        <>
          <FormField
            control={form.control}
            name="price"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Budget/Price Range (optional)</FormLabel>
                <FormControl>
                  <Input
                    type="text"
                    placeholder="e.g., 2,500,000"
                    {...field}
                    value={field.value ? field.value.toLocaleString('en-US') : ""}
                    onChange={(e) => {
                      const rawValue = e.target.value.replace(/[^0-9]/g, '');
                      const val = parseInt(rawValue, 10);
                      field.onChange(isNaN(val) ? undefined : val);
                    }}
                  />
                </FormControl>
                <FormDescription>
                  {listingType === "WANT" ? "Your budget range" :
                   listingType === "RENT" ? "Monthly rent amount" :
                   "Expected price range"}
                </FormDescription>
                <FormMessage />
              </FormItem>
            )}
          />

          {(listingType === "WANT" || listingType === "RENT") && (
            <FormField
              control={form.control}
              name="condition"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Preferred Condition (optional)</FormLabel>
                  <Select value={field.value || "any"} onValueChange={field.onChange}>
                    <FormControl>
                      <SelectTrigger className="w-full">
                        <SelectValue placeholder="Any condition" />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent>
                      <SelectItem value="any">Any condition</SelectItem>
                      <SelectItem value="New">Brand New</SelectItem>
                      <SelectItem value="Reconditioned">Reconditioned</SelectItem>
                      <SelectItem value="Used">Used</SelectItem>
                    </SelectContent>
                  </Select>
                  <FormMessage />
                </FormItem>
              )}
            />
          )}
        </>
      ) : (
        <>
          <FormField
            control={form.control}
            name="price"
            render={({ field }) => (
              <FormItem>
                <div className="flex items-center justify-between">
                  <FormLabel>Price (Rs)</FormLabel>
                  <span className="text-xs text-muted-foreground">Optional</span>
                </div>
                <FormControl>
                  <Input
                    type="text"
                    placeholder="e.g., 2,500,000 (leave blank for Negotiable)"
                    {...field}
                    value={field.value ? field.value.toLocaleString('en-US') : ""}
                    onChange={(e) => {
                      const rawValue = e.target.value.replace(/[^0-9]/g, '');
                      if (!rawValue) {
                        field.onChange(undefined);
                        return;
                      }
                      const val = parseInt(rawValue, 10);
                      field.onChange(isNaN(val) || val <= 0 ? undefined : val);
                    }}
                  />
                </FormControl>
                {field.value ? (
                  <div className="flex items-center justify-between mt-1">
                    <p className="text-xs font-semibold text-teal-700">
                      {formatPrice(field.value)}
                      {form.watch("metadata.isNegotiable" as any) && (
                        <span className="ml-1.5 text-xs text-amber-700 font-medium">(Negotiable)</span>
                      )}
                    </p>
                  </div>
                ) : (
                  <p className="text-xs text-emerald-700 font-medium mt-1">
                    No price specified — ad will be displayed as <strong>&ldquo;Negotiable&rdquo;</strong>
                  </p>
                )}
                <FormMessage />
              </FormItem>
            )}
          />

          {/* Negotiable Checkbox */}
          <FormField
            control={form.control}
            name={"metadata.isNegotiable" as any}
            render={({ field }) => (
              <div className="flex items-center space-x-2.5 bg-slate-50 border border-slate-200/80 rounded-xl p-3">
                <Checkbox
                  id="isNegotiable"
                  checked={!!field.value}
                  onCheckedChange={(checked) => field.onChange(!!checked)}
                  className="data-[state=checked]:bg-teal-700 data-[state=checked]:border-teal-700"
                />
                <label
                  htmlFor="isNegotiable"
                  className="text-xs font-semibold text-slate-700 cursor-pointer select-none flex-1"
                >
                  Price is negotiable
                  <span className="block text-[11px] font-normal text-muted-foreground">
                    Check this if you are willing to negotiate the price with buyers
                  </span>
                </label>
              </div>
            )}
          />

          {/* Dynamic fields based on vehicle type */}
          <DynamicVehicleFieldsStep2 />
        </>
      )}

      <div className="space-y-3 pt-2 border-t">
        <div className="flex items-center justify-between">
          <FormLabel>Description<span className="text-red-500">*</span></FormLabel>
          {listingType === "SELL" && (
            <Button 
              type="button" 
              variant="outline" 
              size="sm" 
              className="h-7 text-xs text-teal-700 border-teal-200 hover:bg-teal-50"
              onClick={autoGenerateDescription}
            >
              <Sparkles className="h-3 w-3 mr-1" /> Auto-generate
            </Button>
          )}
        </div>
        
        <FormField
          control={form.control}
          name="description"
          render={({ field }) => (
            <FormItem>
              <FormControl>
                <Textarea
                  placeholder="Tell potential buyers about your vehicle..."
                  rows={5}
                  {...field}
                />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />

        {listingType === "SELL" && (
          <div className="space-y-2">
            <p className="text-xs text-muted-foreground">Quick add features:</p>
            <div className="flex flex-wrap gap-2">
              {featureChips.map(chip => (
                <button
                  key={chip}
                  type="button"
                  onClick={() => addFeature(chip)}
                  className="inline-flex items-center rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 text-xs font-semibold text-slate-600 hover:bg-teal-50 hover:text-teal-700 hover:border-teal-200 transition-colors"
                >
                  <PlusCircle className="h-3 w-3 mr-1" />
                  {chip}
                </button>
              ))}
            </div>
          </div>
        )}
      </div>

      <div className="flex space-x-3">
        <Button
          type="button"
          variant="outline"
          className="w-1/2"
          onClick={onBack}
        >
          Back
        </Button>
        <Button
          type="button"
          className="w-1/2 bg-teal-700 hover:bg-teal-800 cursor-pointer active:scale-[0.98] transition-all"
          onClick={handleNextClick}
        >
          Continue
        </Button>
      </div>
    </div>
  );
}
