"use client";

import { useFormContext } from "react-hook-form";
import { CreateAdSchema } from "@/server/routes/ad/ad.schemas";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { Button } from "@/components/ui/button";
import { FormField, FormItem, FormLabel, FormControl, FormMessage, FormDescription } from "@/components/ui/form";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { DynamicVehicleFieldsStep2 } from "@/app/(frontend)/(landing)/sell/new/_components/dynamic-vehicle-fields-step-2";
import { Sparkles, PlusCircle } from "lucide-react";

interface Step2Props {
  onBack: () => void;
  onNext: () => void;
  canProceed: boolean;
}

export function Step2VehicleDetails({ onBack, onNext, canProceed }: Step2Props) {
  const form = useFormContext<CreateAdSchema>();
  const listingType = form.watch("listingType");

  const formatPrice = (value: number | undefined) => {
    if (!value) return "";
    return new Intl.NumberFormat('en-LK', { style: 'currency', currency: 'LKR', maximumFractionDigits: 0 }).format(value);
  };

  const autoGenerateDescription = () => {
    const v = form.getValues();
    if (v.listingType !== "SELL") return;
    
    let desc = `For sale: ${v.condition || "Used"} ${v.brand || ""} ${v.model || ""} ${v.manufacturedYear || v.modelYear || ""}`;
    if (["CAR", "VAN", "SUV", "MOTORCYCLE"].includes(v.type)) {
      desc += `.\n\nExcellent condition, carefully used.`;
      if (v.mileage) desc += `\nMileage: ${v.mileage} km.`;
      if (v.engineCapacity) desc += `\nEngine: ${v.engineCapacity} cc.`;
      if (v.transmission) desc += `\nTransmission: ${v.transmission}.`;
      if (v.fuelType) desc += `\nFuel Type: ${v.fuelType}.`;
    } else {
      desc += `.\n\nExcellent condition.`;
    }
    desc += `\n\nLooking for a quick sale. Please contact for more details and to arrange a viewing.`;
    
    form.setValue("description", desc.replace(/\s+/g, ' ').replace(/\. \./g, '.').replace(/ \./g, '.').replace(/For sale: Used \./g, 'For sale: Used.').trim() + "\n\nExcellent condition.\nLooking for a quick sale. Please contact for more details.", { shouldValidate: true });
    
    // Better auto description formatting
    let newDesc = `For sale: ${v.condition || "Used"} ${v.brand || ""} ${v.model || ""} ${v.manufacturedYear || v.modelYear || ""}`.trim();
    if (newDesc.endsWith("Used") || newDesc.endsWith("sale:")) newDesc = "Vehicle for sale";
    
    newDesc += `.\n\nExcellent condition, carefully used.`;
    if (v.mileage) newDesc += `\nMileage: ${v.mileage} km.`;
    if (v.engineCapacity) newDesc += `\nEngine: ${v.engineCapacity} cc.`;
    if (v.transmission) newDesc += `\nTransmission: ${v.transmission}.`;
    if (v.fuelType) newDesc += `\nFuel Type: ${v.fuelType}.`;
    
    newDesc += `\n\nLooking for a quick sale. Please contact for more details.`;
    form.setValue("description", newDesc, { shouldValidate: true });
  };

  const featureChips = ["A/C", "Power Steering", "Power Windows", "ABS", "Reverse Camera", "Alloy Wheels", "Sunroof", "First Owner"];
  const addFeature = (feature: string) => {
    const currentDesc = form.getValues("description") || "";
    const newDesc = currentDesc ? `${currentDesc}\n- ${feature}` : `- ${feature}`;
    form.setValue("description", newDesc, { shouldValidate: true });
  };

  return (
    <div className="space-y-6">
      {listingType !== "SELL" ? (
        <>
          <FormField
            control={form.control}
            name="price"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Budget/Price Range (optional)</FormLabel>
                <FormControl>
                  <Input
                    type="text"
                    placeholder="e.g., 2,500,000"
                    {...field}
                    value={field.value ? field.value.toLocaleString('en-US') : ""}
                    onChange={(e) => {
                      const rawValue = e.target.value.replace(/[^0-9]/g, '');
                      const val = parseInt(rawValue, 10);
                      field.onChange(isNaN(val) ? undefined : val);
                    }}
                  />
                </FormControl>
                <FormDescription>
                  {listingType === "WANT" ? "Your budget range" :
                   listingType === "RENT" ? "Monthly rent amount" :
                   "Expected price range"}
                </FormDescription>
                <FormMessage />
              </FormItem>
            )}
          />

          {(listingType === "WANT" || listingType === "RENT") && (
            <FormField
              control={form.control}
              name="condition"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Preferred Condition (optional)</FormLabel>
                  <Select value={field.value || "any"} onValueChange={field.onChange}>
                    <FormControl>
                      <SelectTrigger className="w-full">
                        <SelectValue placeholder="Any condition" />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent>
                      <SelectItem value="any">Any condition</SelectItem>
                      <SelectItem value="New">Brand New</SelectItem>
                      <SelectItem value="Reconditioned">Reconditioned</SelectItem>
                      <SelectItem value="Used">Used</SelectItem>
                    </SelectContent>
                  </Select>
                  <FormMessage />
                </FormItem>
              )}
            />
          )}
        </>
      ) : (
        <>
          <FormField
            control={form.control}
            name="price"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Price (Rs)</FormLabel>
                <FormControl>
                  <Input
                    type="text"
                    placeholder="e.g., 2,500,000"
                    {...field}
                    value={field.value ? field.value.toLocaleString('en-US') : ""}
                    onChange={(e) => {
                      const rawValue = e.target.value.replace(/[^0-9]/g, '');
                      const val = parseInt(rawValue, 10);
                      field.onChange(isNaN(val) ? undefined : val);
                    }}
                  />
                </FormControl>
                {field.value ? (
                  <p className="text-xs font-medium text-teal-700 mt-1">{formatPrice(field.value)}</p>
                ) : null}
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="metadata"
            render={({ field }) => {
              const isNegotiable = field.value?.isNegotiable || false;
              return (
                <FormItem className="flex flex-row items-start space-x-3 space-y-0 rounded-md p-2">
                  <FormControl>
                    <Checkbox
                      checked={isNegotiable}
                      onCheckedChange={(checked) => {
                        field.onChange({
                          ...(field.value || {}),
                          isNegotiable: checked
                        });
                      }}
                    />
                  </FormControl>
                  <div className="space-y-1 leading-none">
                    <FormLabel className="text-sm font-medium cursor-pointer">
                      Price is Negotiable
                    </FormLabel>
                  </div>
                </FormItem>
              );
            }}
          />

          {/* Dynamic fields based on vehicle type */}
          <DynamicVehicleFieldsStep2 />
        </>
      )}

      <div className="space-y-3 pt-2 border-t">
        <div className="flex items-center justify-between">
          <FormLabel>Description<span className="text-red-500">*</span></FormLabel>
          {listingType === "SELL" && (
            <Button 
              type="button" 
              variant="outline" 
              size="sm" 
              className="h-7 text-xs text-teal-700 border-teal-200 hover:bg-teal-50"
              onClick={autoGenerateDescription}
            >
              <Sparkles className="h-3 w-3 mr-1" /> Auto-generate
            </Button>
          )}
        </div>
        
        <FormField
          control={form.control}
          name="description"
          render={({ field }) => (
            <FormItem>
              <FormControl>
                <Textarea
                  placeholder="Tell potential buyers about your vehicle..."
                  rows={5}
                  {...field}
                />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />

        {listingType === "SELL" && (
          <div className="space-y-2">
            <p className="text-xs text-muted-foreground">Quick add features:</p>
            <div className="flex flex-wrap gap-2">
              {featureChips.map(chip => (
                <button
                  key={chip}
                  type="button"
                  onClick={() => addFeature(chip)}
                  className="inline-flex items-center rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 text-xs font-semibold text-slate-600 hover:bg-teal-50 hover:text-teal-700 hover:border-teal-200 transition-colors"
                >
                  <PlusCircle className="h-3 w-3 mr-1" />
                  {chip}
                </button>
              ))}
            </div>
          </div>
        )}
      </div>

      <div className="flex space-x-3">
        <Button
          type="button"
          variant="outline"
          className="w-1/2"
          onClick={onBack}
        >
          Back
        </Button>
        <Button
          type="button"
          className="w-1/2 bg-teal-700 hover:bg-teal-800"
          onClick={onNext}
          disabled={!canProceed}
        >
          Continue
        </Button>
      </div>
    </div>
  );
}
